// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiaeyhUpHcXFAuPqHmc2PIn_YwJGwA8Js',
    appId: '1:1074664684630:web:49a2ad48e81ff4c3964ff7',
    messagingSenderId: '1074664684630',
    projectId: 'honeypot01-bdd42',
    authDomain: 'honeypot01-bdd42.firebaseapp.com',
    storageBucket: 'honeypot01-bdd42.firebasestorage.app',
    measurementId: 'G-Z31F5V5E02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCylKyBXfGfGgJAacczk0GHF2BvRdhcuhY',
    appId: '1:1074664684630:android:f0922c545c317c69964ff7',
    messagingSenderId: '1074664684630',
    projectId: 'honeypot01-bdd42',
    storageBucket: 'honeypot01-bdd42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZxkLvQGkfJw1exFem38vmaUuDdY_j5lk',
    appId: '1:1074664684630:ios:fd2d8d65eed451b2964ff7',
    messagingSenderId: '1074664684630',
    projectId: 'honeypot01-bdd42',
    storageBucket: 'honeypot01-bdd42.firebasestorage.app',
    iosBundleId: 'cmc.cs.honeypot01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZxkLvQGkfJw1exFem38vmaUuDdY_j5lk',
    appId: '1:1074664684630:ios:fd2d8d65eed451b2964ff7',
    messagingSenderId: '1074664684630',
    projectId: 'honeypot01-bdd42',
    storageBucket: 'honeypot01-bdd42.firebasestorage.app',
    iosBundleId: 'cmc.cs.honeypot01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiaeyhUpHcXFAuPqHmc2PIn_YwJGwA8Js',
    appId: '1:1074664684630:web:e202659875254607964ff7',
    messagingSenderId: '1074664684630',
    projectId: 'honeypot01-bdd42',
    authDomain: 'honeypot01-bdd42.firebaseapp.com',
    storageBucket: 'honeypot01-bdd42.firebasestorage.app',
    measurementId: 'G-8MPL66J8LE',
  );
}
